javascript:
  vendor:
    require:
      - core-js
      - react
      - redux
      - react-redux
      - redux-thunk
      - moment
  application:
    external:
      - react
      - moment
      - redux
      - react-redux
      - redux-thunk
